backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "index.html"
        label: "Portfolio Content"
        name: "portfolio"
        fields:
          - { label: "Your Name", name: "name", widget: "string" }
          - { label: "About Text", name: "about", widget: "text" }
          - { label: "Contact Email", name: "email", widget: "string" }

  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Project URL", name: "url", widget: "string" }
